# Generated by Django 5.2.7 on 2025-10-13 04:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_modify_username_validator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='DOCENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con ese nombre.'}, help_text='Requerido. 150 caracteres o menos. Letras, dígitos, espacios y @/./+/-/_ solamente.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='El nombre de usuario puede contener letras, números, espacios y caracteres especiales', regex='^[\\w\\sñÑáéíóúÁÉÍÓÚüÜ.,@+-]+$')]),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
