# Generated by Django 5.2.7 on 2025-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_remove_user_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCENTE', 'Docente')], default='DOCENTE', max_length=20),
        ),
    ]
