# Generated by Django 5.2.7 on 2025-10-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Aula')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad Máxima')),
                ('tipo', models.CharField(choices=[('TEORIA', 'Aula de Teoría'), ('LABORATORIO', 'Laboratorio'), ('MIXTA', 'Aula Mixta')], default='TEORIA', max_length=20)),
                ('edificio', models.CharField(blank=True, max_length=50, verbose_name='Edificio')),
                ('piso', models.CharField(blank=True, max_length=10, verbose_name='Piso')),
                ('tiene_proyector', models.BooleanField(default=False, verbose_name='Tiene Proyector')),
                ('tiene_computadoras', models.BooleanField(default=False, verbose_name='Tiene Computadoras')),
                ('tiene_pizarra_digital', models.BooleanField(default=False, verbose_name='Tiene Pizarra Digital')),
                ('equipamiento_adicional', models.TextField(blank=True, verbose_name='Equipamiento Adicional')),
                ('activa', models.BooleanField(default=True, verbose_name='Aula Activa')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['edificio', 'piso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Curso')),
                ('creditos', models.IntegerField(verbose_name='Número de Créditos')),
                ('tipo', models.CharField(choices=[('OBLIGATORIO', 'Obligatorio'), ('ELECTIVO', 'Electivo'), ('OPTATIVO', 'Optativo')], default='OBLIGATORIO', max_length=20)),
                ('sesiones_semana', models.IntegerField(default=1, verbose_name='Sesiones por Semana')),
                ('duracion_sesion', models.IntegerField(default=2, verbose_name='Duración de Sesión (horas)')),
                ('capacidad_estimada', models.IntegerField(default=30, verbose_name='Capacidad Estimada de Estudiantes')),
                ('equipamiento_requerido', models.TextField(blank=True, verbose_name='Equipamiento Requerido')),
                ('activo', models.BooleanField(default=True, verbose_name='Curso Activo')),
                ('requisitos', models.ManyToManyField(blank=True, to='academic.curso', verbose_name='Prerrequisitos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['codigo'],
            },
        ),
    ]
