# Generated by Django 5.2.7 on 2025-10-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='requiere_laboratorio',
            field=models.BooleanField(default=False, verbose_name='Requiere Laboratorio'),
        ),
    ]
