# Generated by Django 5.2.7 on 2025-10-12 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=20, verbose_name='Día de la Semana')),
                ('bloque_horario', models.CharField(choices=[('08:00-10:00', '08:00 - 10:00'), ('10:00-12:00', '10:00 - 12:00'), ('12:00-14:00', '12:00 - 14:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00'), ('18:00-20:00', '18:00 - 20:00')], max_length=20, verbose_name='Bloque Horario')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('activa', models.BooleanField(default=True, verbose_name='Asignación Activa')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aula', verbose_name='Aula')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.curso', verbose_name='Curso')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Asignación',
                'verbose_name_plural': 'Asignaciones',
                'ordering': ['dia_semana', 'bloque_horario'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Horario')),
                ('semestre', models.CharField(max_length=20, verbose_name='Semestre Académico')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'Generado'), ('APROBADO', 'Aprobado'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='BORRADOR', max_length=20)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConflictoHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conflicto', models.CharField(choices=[('DOCENTE', 'Conflicto de Docente'), ('AULA', 'Conflicto de Aula'), ('CURSO', 'Conflicto de Curso'), ('CAPACIDAD', 'Conflicto de Capacidad')], max_length=20, verbose_name='Tipo de Conflicto')),
                ('descripcion', models.TextField(verbose_name='Descripción del Conflicto')),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Detección')),
                ('resuelto', models.BooleanField(default=False, verbose_name='Conflicto Resuelto')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Resolución')),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.asignacion', verbose_name='Asignación Conflictiva')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflictos', to='schedule.horario')),
            ],
            options={
                'verbose_name': 'Conflicto de Horario',
                'verbose_name_plural': 'Conflictos de Horario',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.AddField(
            model_name='asignacion',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='schedule.horario'),
        ),
        migrations.AlterUniqueTogether(
            name='asignacion',
            unique_together={('horario', 'aula', 'dia_semana', 'bloque_horario'), ('horario', 'curso', 'dia_semana', 'bloque_horario'), ('horario', 'docente', 'dia_semana', 'bloque_horario')},
        ),
    ]
