# Generated by Django 5.2.7 on 2025-10-13 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conflictohorario',
            name='tipo_conflicto',
            field=models.CharField(choices=[('DOCENTE', 'Conflicto de Docente'), ('AULA', 'Conflicto de Aula'), ('CURSO', 'Conflicto de Curso'), ('CAPACIDAD', 'Conflicto de Capacidad'), ('EQUIPAMIENTO', 'Conflicto de Equipamiento')], max_length=20, verbose_name='Tipo de Conflicto'),
        ),
        migrations.CreateModel(
            name='DisponibilidadDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=20, verbose_name='Día de la Semana')),
                ('bloque_horario', models.CharField(choices=[('08:00-10:00', '08:00 - 10:00'), ('10:00-12:00', '10:00 - 12:00'), ('12:00-14:00', '12:00 - 14:00'), ('14:00-16:00', '14:00 - 16:00'), ('16:00-18:00', '16:00 - 18:00'), ('18:00-20:00', '18:00 - 20:00')], max_length=20, verbose_name='Bloque Horario')),
                ('disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Disponibilidad de Docente',
                'verbose_name_plural': 'Disponibilidades de Docentes',
                'ordering': ['docente', 'dia_semana', 'bloque_horario'],
                'unique_together': {('docente', 'dia_semana', 'bloque_horario')},
            },
        ),
    ]
