# Generated by Django 5.2.7 on 2025-10-19 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_conflictohorario_tipo_conflicto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioPersonalizadoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('LUNES', 'Lunes'), ('MARTES', 'Martes'), ('MIERCOLES', 'Miércoles'), ('JUEVES', 'Jueves'), ('VIERNES', 'Viernes'), ('SABADO', 'Sábado')], max_length=20, verbose_name='Día de la Semana')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('tipo', models.CharField(choices=[('DISPONIBLE', '✅ Horario Disponible'), ('NO_DISPONIBLE', '🚫 Horario No Disponible')], default='DISPONIBLE', max_length=20, verbose_name='Tipo de Horario')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Reunión de departamento, Investigación, etc.', max_length=200, verbose_name='Descripción (opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('docente', models.ForeignKey(limit_choices_to={'rol': 'DOCENTE'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Horario Personalizado de Docente',
                'verbose_name_plural': 'Horarios Personalizados de Docentes',
                'ordering': ['docente', 'dia_semana', 'hora_inicio'],
                'unique_together': {('docente', 'dia_semana', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
